version: '3.8'

services:
  frontend:
    image: jimsonxd/react-image:latest
    ports:
      - 3000:3000
    networks:
      - team3network

  backend:
    image: jimsonxd/express-image:latest
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    networks:
      - team3network

  mongodb:
    image: mongo:6
    volumes: 
      - database:/data/db
    ports:
      - 27018:27017
    networks:
      - team3network

volumes:
  database:

networks:
  team3network: