name: Netlify Deployment

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Navigate to React app folder
        working-directory: ./Mission5/react
        run: cd react

      - name: Install React dependencies and build
        run: |
          npm install
          npm run build
        env:
          CI: true

      - name: Navigate to Express app folder
        working-directory: ./Mission5/express
        run: cd express

      - name: Install Express dependencies and start server
        run: |
          npm install
          npm start

      - name: Deploy to Netlify
        run: |
          npm install -g netlify-cli
          netlify login # You might need to set up Netlify authentication before running this command
          netlify deploy --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
