name: Build and Push Docker Images to DockerHub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Express Docker image
        working-directory: ./express
        run: |
          docker build -t jimsonxd/express-image:latest .
          docker push jimsonxd/express-image:latest

      - name: Build and push React Docker image
        working-directory: ./react
        run: |
          docker build -t jimsonxd/react-image:latest .
          docker push jimsonxd/react-image:latest
