name: Build and Push Docker Image

on:
  push:
    branches:
      - main # You can change this to the branch you want to trigger the workflow
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t jimsonxd/frontend:latest .
        working-directory: .

      - name: Push Docker image to Docker Hub
        run: |
          docker push jimsonxd/frontend:latest

