name: CI

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: "16.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies (Express app)
        run: npm ci
        working-directory: ./MRL5_Mission5/express

      - name: Build (Express app)
        run: npm run build
        working-directory: ./MRL5_Mission5/express

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies (Express app)
        run: npm ci
        working-directory: ./Mission5/express

      - name: Run Tests (Express app)
        run: npm test
        working-directory: ./Mission5/express
